apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmage
  namespace: xmage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: xmage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xmage
    spec:
      hostAliases:
        - ip: "0.0.0.0"
          hostnames:
            - localhost
      containers:
        - name: xmage
          image: unstoppablemango/mage-server:v1.4.58V1r1
          env:
            - name: XMAGE_SERVER_NAME
              value: THECLUSTER
            - name: XMAGE_SERVER_ADDRESS
              value: localhost
            - name: XMAGE_PORT
              value: "17171"
            - name: MAX_MEMORY
              value: 4g
            - name: MIN_MEMORY
              value: 256m
          ports:
            - containerPort: 17171
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: db
              mountPath: /opt/xmage/db
            - name: saved
              mountPath: /opt/xmage/saved
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
        - name: saved
          emptyDir: {}
