apiVersion: v1
kind: Service
metadata:
  name: xmage
  namespace: xmage
spec:
  selector:
    app.kubernetes.io/name: xmage
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 17171
      targetPort: 17171
