apiVersion: apps/v1
kind: Deployment
metadata:
  name: necesse
  namespace: necesse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: necesse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: necesse
    spec:
      containers:
        - name: necesse
          image: ghcr.io/brammys/necesse-server:1-1-1-21292486
          env:
            - name: PAUSE
              value: "1"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: necesse
                  key: password
          resources:
            limits:
              memory: "8Gi"
              cpu: "4"
            requests:
              memory: "8Gi"
              cpu: "4"
          ports:
            - containerPort: 14159
              name: game
          volumeMounts:
            - name: saves
              mountPath: /necesse/saves
      volumes:
        - name: saves
          persistentVolumeClaim:
            claimName: necesse
