apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ncps
  namespace: nix-system
spec:
  ingressClassName: nginx
  rules:
  - host: ncps.thecluster.lan
    http:
      paths:
      - backend:
          service:
            name: ncps
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ncps.thecluster.lan
    secretName: ncps-tls
