apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ncps
  namespace: nix-system
  annotations:
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer: thecluster.lan
spec:
  ingressClassName: nginx
  rules:
  - host: ncps.thecluster.lan
    http:
      paths:
      - backend:
          service:
            name: ncps
            port:
              name: http-web
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ncps.thecluster.lan
    secretName: ncps-tls
