apiVersion: v1
kind: Service
metadata:
  name: ncps
  namespace: nix-system
  labels:
    app: ncps
    tier: proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-web
      port: 8501
  selector:
    app: ncps
    tier: proxy
