name: Rosequartz End To End Test

on:
  pull_request:
    branches: [main]
    paths:
      - .github/actions/rosequartz-e2e-test/**
      - .github/workflows/rosequartz-e2e-test.yaml
      - apps/crds/package-lock.json
      - apps/cert-manager/package-lock.json
      - apps/cert-manager/Chart.lock
      - apps/clusterapi/package-lock.json
      - apps/metrics-server/package-lock.json
      - apps/metrics-server/Chart.lock
      - clusters/rosequartz/package-lock.json
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: thecluster
    container:
      image: ghcr.io/unstoppablemango/runner-image:main
      options: pull=always
    if: false # Still some kinks to work out
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      STACK: e2e-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "/__w/the-cluster/the-cluster" # actions/runner#2033

      - uses: pulumi/actions@v5
        with:
          pulumi-version: 3.101.0 # renovate depName=pulumi/pulumi extractVersion=^v(?<version>.*)
          comment-on-pr: false
          comment-on-summary: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create test node
        working-directory: clusters/rosequartz
        run: docker compose -f hack/docker-compose.yaml up -d

      - uses: ./.github/actions/rosequartz-e2e-test
        with:
          stack: ${{ env.STACK }}
          endpoint: ${{ secrets.RQ_PRIMARY_DNS_NAME }}

      - name: Tear down Cluster API
        if: always()
        continue-on-error: true
        working-directory: apps/clusterapi
        run: pulumi stack rm -yf "${{ env.STACK }}"

      - name: Tear down metrics-server
        if: always()
        continue-on-error: true
        working-directory: apps/metrics-server
        run: pulumi stack rm -yf "${{ env.STACK }}"

      - name: Tear down cert-manager
        if: always()
        continue-on-error: true
        working-directory: apps/cert-manager
        run: pulumi stack rm -yf "${{ env.STACK }}"

      - name: Tear down rosequartz
        if: always()
        continue-on-error: true
        working-directory: clusters/rosequartz
        run: pulumi stack rm -yf "${{ env.STACK }}"

  upgrade-e2e-test:
    runs-on: thecluster
    container:
      image: ghcr.io/unstoppablemango/runner-image:main
      options: pull=always
    if: false # We need the pulumi code to exist on main in order to test an upgrade
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      STACK: upgrade-e2e-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "/__w/the-cluster/the-cluster" # actions/runner#2033
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            apps
            clusters

      - uses: pulumi/actions@v5
        with:
          pulumi-version: 3.101.0 # renovate depName=pulumi/pulumi extractVersion=^v(?<version>.*)
          comment-on-pr: false
          comment-on-summary: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create test node
        working-directory: clusters/rosequartz
        run: docker compose -f hack/docker-compose.yaml up -d
        shell: bash

      - uses: ./.github/actions/rosequartz-e2e-test
        with:
          stack: ${{ env.STACK }}
          endpoint: ${{ secrets.RQ_PRIMARY_DNS_NAME }}

      - uses: actions/checkout@v4

      - uses: ./.github/actions/rosequartz-e2e-test
        with:
          stack: ${{ env.STACK }}
          endpoint: ${{ secrets.RQ_PRIMARY_DNS_NAME }}

      - name: Tear down Cluster API
        if: always()
        continue-on-error: true
        working-directory: apps/clusterapi
        run: pulumi stack rm -yf "${{ env.STACK }}"

      - name: Tear down metrics-server
        if: always()
        continue-on-error: true
        working-directory: apps/metrics-server
        run: pulumi stack rm -yf "${{ env.STACK }}"

      - name: Tear down cert-manager
        if: always()
        continue-on-error: true
        working-directory: apps/cert-manager
        run: pulumi stack rm -yf "${{ env.STACK }}"

      - name: Tear down rosequartz
        if: always()
        continue-on-error: true
        working-directory: clusters/rosequartz
        run: pulumi stack rm -yf "${{ env.STACK }}"
